---
name: Publish bundle to nexus-casc-plugin release

on:
  release:
    types: [created]
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        run: ./mvnw -B package --file pom.xml

      - name: Stage
        run: mkdir staging && cp target/*.kar staging

      - name: release
        uses: ncipollo/release-action@v1.12.0
        id: create_release
        with:
          artifacts: 'staging/*'
