---
name: Publish bundle to nexus-casc-plugin release

on:
  release:
    types: [created]
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build
        run: ./mvnw -B package --file pom.xml

      - name: Stage
        run: mkdir staging && cp target/*.kar staging

      - name: release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          artifacts: 'staging/*'
